type: redis
secret: ch@ngfengpol@nghuiyoushi!!!!!!!!
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0

log:
  file: error.log  # 仅测试用
  rsyslog:
    host: 127.0.0.1
    port: 514
    type: tcp
  #kafka:
  #  topic: ztgw
  #  broker:
  #    -
  #      host: 127.0.0.1
  #      port: 9092
  #    - host: 192.168.91.100
  #      port: 9092
